// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusOk HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case HealthResponseStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for ReadyResponseStatus.
const (
	ReadyResponseStatusNotReady ReadyResponseStatus = "not_ready"
	ReadyResponseStatusOk       ReadyResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the ReadyResponseStatus enum.
func (e ReadyResponseStatus) Valid() bool {
	switch e {
	case ReadyResponseStatusNotReady:
		return true
	case ReadyResponseStatusOk:
		return true
	default:
		return false
	}
}

// EchoRequest defines model for EchoRequest.
type EchoRequest struct {
	Message string `json:"message"`
}

// EchoResponse defines model for EchoResponse.
type EchoResponse struct {
	Message string `json:"message"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error struct {
		Code      string                       `json:"code"`
		Details   *ErrorEnvelope_Error_Details `json:"details,omitempty"`
		Message   string                       `json:"message"`
		RequestId string                       `json:"request_id"`
	} `json:"error"`
}

// ErrorEnvelope_Error_Details defines model for ErrorEnvelope.Error.Details.
type ErrorEnvelope_Error_Details struct {
	Fields *[]struct {
		Code    string `json:"code"`
		Field   string `json:"field"`
		Message string `json:"message"`
	} `json:"fields,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// ReadyResponse defines model for ReadyResponse.
type ReadyResponse struct {
	Status ReadyResponseStatus `json:"status"`
}

// ReadyResponseStatus defines model for ReadyResponse.Status.
type ReadyResponseStatus string

// Error defines model for Error.
type Error = ErrorEnvelope

// PostEchoJSONRequestBody defines body for PostEcho for application/json ContentType.
type PostEchoJSONRequestBody = EchoRequest

// Getter for additional properties for ErrorEnvelope_Error_Details. Returns the specified
// element and whether it was found
func (a ErrorEnvelope_Error_Details) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ErrorEnvelope_Error_Details
func (a *ErrorEnvelope_Error_Details) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ErrorEnvelope_Error_Details to handle AdditionalProperties
func (a *ErrorEnvelope_Error_Details) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["fields"]; found {
		err = json.Unmarshal(raw, &a.Fields)
		if err != nil {
			return fmt.Errorf("error reading 'fields': %w", err)
		}
		delete(object, "fields")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ErrorEnvelope_Error_Details to handle AdditionalProperties
func (a ErrorEnvelope_Error_Details) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Fields != nil {
		object["fields"], err = json.Marshal(a.Fields)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fields': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Liveness probe
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// GetReady Readiness probe
	// (GET /ready)
	GetReady(w http.ResponseWriter, r *http.Request)
	// PostEcho Bootstrap validation probe
	// (POST /v1/echo)
	PostEcho(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// GetHealth Liveness probe
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetReady Readiness probe
// (GET /ready)
func (_ Unimplemented) GetReady(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PostEcho Bootstrap validation probe
// (POST /v1/echo)
func (_ Unimplemented) PostEcho(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReady operation middleware
func (siw *ServerInterfaceWrapper) GetReady(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReady(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEcho operation middleware
func (siw *ServerInterfaceWrapper) PostEcho(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEcho(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ready", wrapper.GetReady)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/echo", wrapper.PostEcho)
	})

	return r
}

type ErrorJSONResponse ErrorEnvelope

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyRequestObject struct {
}

type GetReadyResponseObject interface {
	VisitGetReadyResponse(w http.ResponseWriter) error
}

type GetReady200JSONResponse ReadyResponse

func (response GetReady200JSONResponse) VisitGetReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReady503JSONResponse ReadyResponse

func (response GetReady503JSONResponse) VisitGetReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type PostEchoRequestObject struct {
	Body *PostEchoJSONRequestBody
}

type PostEchoResponseObject interface {
	VisitPostEchoResponse(w http.ResponseWriter) error
}

type PostEcho200JSONResponse EchoResponse

func (response PostEcho200JSONResponse) VisitPostEchoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostEcho400JSONResponse struct{ ErrorJSONResponse }

func (response PostEcho400JSONResponse) VisitPostEchoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Liveness probe
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// GetReady Readiness probe
	// (GET /ready)
	GetReady(ctx context.Context, request GetReadyRequestObject) (GetReadyResponseObject, error)
	// PostEcho Bootstrap validation probe
	// (POST /v1/echo)
	PostEcho(ctx context.Context, request PostEchoRequestObject) (PostEchoResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReady operation middleware
func (sh *strictHandler) GetReady(w http.ResponseWriter, r *http.Request) {
	var request GetReadyRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReady(ctx, request.(GetReadyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReady")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadyResponseObject); ok {
		if err := validResponse.VisitGetReadyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostEcho operation middleware
func (sh *strictHandler) PostEcho(w http.ResponseWriter, r *http.Request) {
	var request PostEchoRequestObject

	var body PostEchoJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostEcho(ctx, request.(PostEchoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostEcho")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostEchoResponseObject); ok {
		if err := validResponse.VisitPostEchoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xFlfk9u2Ef8qGLYP6YwkXOLmRTN9uNRu7DZtND4nffDdeCBgRSJHAggW5Fnh6Lt3FiQlUsTJl+Y8fhK4",
	"+8Ni/wC7C6jNpK2cNWACZus284DOGoT48cp762kgrQlgAg2Fc6WWImhr+C9oDdFQFlAJGv3Zwy5bZ3/i",
	"J6m84yKP0l6ZBkrrIDscDotMAUqvHQnL1tlNEEYJrxgQksEJuuiX6LSShX0Lv9aAnUJKaRIgyo23DnzQ",
	"pPxOlAiLzI1IbVYBosiBhmHvIFtnGLw2eVzBw6+19qCy9fsj8G4xAO32F5AhOyz65TsvfZH1J278fQrA",
	"ENDfMUdaldKYgheELvFxccHXM2k7DaWKIx2gwufSJYpNcp7s807EoltjcTEEPUF4L/ZRzgzx+KrdooDh",
	"g1afVupMmcnkuWZnk7topwx4DaIMxf+5izGIUHfbydQVLWTvR6s8Ykk/K6XNWxBq/5zKLDJjwwdPYv+A",
	"YpR1QNZeh/0NZZ9uwS0ID/66DsXp6x/WVyJk6+yf/32X9bmKJHXc7Ci5CMGRwdLaew2DjGkSJMyPptyz",
	"G1obmIedByxYsPdgWDeTIQRmDQsFsOvNG1ZYDNki0zS/Q5ALRNShn/8hzj+pIpz+F+y7LKzNzs4Vef3u",
	"3YZR4vdCBrazPi73/b7a1CUC+94yBN+AX92ajQgFMuEhQpy3qpaBSRFEafMVey2MKsF3CF25EiowARRz",
	"4NmPDsyNA8lkIUwOq1vzSsiCUYxjkWEaWSX8PSi2KQQC+/fPG2Y9+0EE8CtmhdNLOiU5eaf2Hkwo9ywH",
	"Q/MBb4018Tt0e35Bw7jhFkwYxZzFQBmd1SboMupvH4w2ea8PLR9LHqjVbfSfDiU58OiI682bbJE14LHz",
	"29XqavUNRdk6MMLpbJ29WH29usoWmSM/kad5EZWhYQ5h7vto6ZpVjVuxv0c91mxrbcDghVv2fmdvu12M",
	"a+bqbaklUULtDbJvrq6Y3g3RkIBIdvjakGUr9tICMmMDc2QooZQIYisQOhuPzn+jyNLBdzH9jNqDb66u",
	"nq05OMtIie5gczKkdpPTma3f3y0yrKtK+H22zn7QDRiCOm+3dBSCyJGOeu/1u0X2cZnvK0fxW3ZxptN6",
	"5uBsAnMUkmydVY2bMvpcgtk668IQdeNd9vmcAX4owEyC14UTaykBFC6YDQX4B43Avr168Uhk41H4nIGd",
	"JvdEXF8O2tMOBSELsS2Bzs+3Vy++jBZ0MkaaXNhpJFZ/8a3WfM1FrXRYQtO38UdqKPhpLftgwJ9xtWl0",
	"gCSRCynBhTNeaXOqM+c0W58DnUB8sF7xweo0d2d9bh+d6wHhnNlXtDNqA17v9kuohC7TLFdYA0kWl9bs",
	"tK9OzK0uS21yLgUWy9rNGbYBr+qRuC3VXZMjb/vRG3UYcb0wsgCcU3jbjZLwEZMLLwvdwGVQYWs/WkQW",
	"IO+1SVC4A3G/fATOHfndhAQHg9jtEvQ27r2JEbIUiEs6gaoux6afMXg7DBPTqV3BJJG38ePd3k3ngSxi",
	"N0OV/fkSL/UIgEywvhVfsZ8QFAuWwUfwkpIsdTLUjfUtOmtEqVVMVqtb8xKaJXUiaxYKjQyMclabEKuZ",
	"8ZBrDOBBdUn9erP58Oo/P/+t76RIAnsLlW2AWSOBCUpP5bAAqJM4+KgxYCrXb/pG53SH+M52Bep5Lvej",
	"S/lh2mLTNfDwGSvM5EKeSO0xdGoIHFWWv3arp4QeteyeKy5m/++GfTMK9bMWAtVvmuEq/cdqBDFcNTnW",
	"w97FBIm3w3ByvHZ6cpbjJ2/pZw470vkp0Gk+6tyAWtZ+lLvzfTX5iAlP0RVuQi0s+X6PaSpv+9FEO20a",
	"q+XYjoHC236UxI+5XGmUth4blYQ5sa+mZTkJ8yBBu08Ja2x8NeghJQiFZ5+8pZ+J9lM6xaIBHx7lGxvG",
	"nqlgPB4y/rK7T044pZ7aWQFHQLoWpYm87UcTbSuotuBxRuDw0dmx2gNdV2l62w1Swke8eV1NYHIrSryI",
	"qEBg7aE690ACGEmFdpdxsyjMEPONlQJ5m3vAp4GoRQr2MtYDBusvuyt4oQ345adteLD+3tZh6UphnoSc",
	"g8iTtDe0n6SGMbc9fcQDIIyE8knQnQf4DZ4E9WDg4YlIrKunCa1d7oUaYY0NetfXSXyEzDF4EKPkOd8p",
	"A4W3/ajTa1ebUXo5C0r85C39TM6U87ay8Q1mDA7L+dkfEXnrwk3i9LsaC471lgr4dmS3BzrkyIUMuoHl",
	"LEkc+SGAURTgOU8WtTcJcuwp66BL/ZvoeoZziKfutk6IpLpVu4QebTc4zLKWt7Ya4edOupwdU9yk0Ung",
	"cEn5BOxB6FBqHGl91vbHT97Gn6l6UwZXEAMmxlfMc4x/Eqax95DYUjOgnbQnfSZKUHjbjyb6p7hcNEKX",
	"YqvL2ANehM5q4CVUskKlJ9iq0oiTvTkEibfDaCLnkcw6IfO2/9ycn+kh2x4RPXfaDU9fw9/fHag9jn0s",
	"Rm5s5zKeEb3vh9vhXbrviw+LI4Uu5PF79q/gbseEjL0Wq4QReSyz8fmWwn16K8bTs3e3YefSrmulAytt",
	"zrrHEvZVfBWJwjrZnlHL/ZeTqPi2MlaUGtO55J8MGQAmUBoG1d8cj1czZF+VXfvKUAdYMGq3mBQu1B5G",
	"qw1N+2m5IdfNSbGJGJG7fnBE6Ju1Mal/wJigKAHCZOLx3Ixoxwo8olEv0F2q2tMfDjEDjknTonW4O/wv",
	"AAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
